name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_COAST_0F5C58210 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "App" # App source code path
          api_location: "Api" # Api source code path - optional
          data_api_location: "Db" # Folder holding the staticwebapps.database.config.json file
          output_location: "wwwroot" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  staging_db:
    if: env.BRANCH_NAME != 'main' # this is for building out dev databases for staging environments, not for migrating prod
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: echo "${{ env.DB_CONNECTION_STRING }}"
      - name: Build Connection String
        run: echo "DB_CONNECTION_STRING=$(echo "${{ env.DB_CONNECTION_STRING }}" | sed 's/%%DB%%/${{ env.BRANCH_NAME }}/g')"  >> $GITHUB_ENV
      - run: echo "${{ env.DB_CONNECTION_STRING }}"
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.202
      - name: Install dotnet-ef tool
        run: dotnet tool install --global dotnet-ef
      - name: Set file permissions
        run: chmod -R 777 ./Db
      - name: Run db-reset
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        run: npm run db-reset
      - name: Run db-drop
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: npm run db-drop
      
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GREEN_COAST_0F5C58210 }}
          action: "close"
